name: Build tt-rss Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'tt-rss/**'
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build info
        id: build-info
        run: |
          echo "date=$(date +'%Y-%m-%d')" >>$GITHUB_OUTPUT \
          && git clone --depth=1 https://git.tt-rss.org/fox/tt-rss.git \
          && echo "hash=$(git -C tt-rss rev-parse --short HEAD)" >>$GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: tt-rss
          build-args: |
            TTRSS_GIT_COMMIT=${{ steps.build-info.outputs.hash }}
          tags: |
            ghcr.io/christoph-heiss/tt-rss:latest
            ghcr.io/christoph-heiss/tt-rss:${{ steps.build-info.outputs.date }}
            ghcr.io/christoph-heiss/tt-rss:${{ steps.build-info.outputs.hash }}
            ghcr.io/christoph-heiss/tt-rss:${{ steps.build-info.outputs.date }}-${{ steps.build-info.outputs.hash }}
